[package]
name = "arb-sys"
version = "0.1.1"
authors = ["William Youmans <wyoumans@usf.edu>"]
edition = "2018"
description = "Bindings to the ARB library"
homepage = "https://github.com/wyoumansUSF/arb-sys"
repository = "https://github.com/wyoumansUSF/arb-sys"
license = "LGPL-3.0+" 
keywords = ["flint", "real", "complex", "number-theory", "math"]
categories = ["algorithms", "external-ffi-bindings", "mathematics"]
readme = "README.md"

[dependencies]
libc = "0.2"
flint-sys = "0.4"
#flint-sys = { path = "../flint-rs/flint-sys" }

#[dev-dependencies]
#quickcheck = "1.0"
#quickcheck_macros = "1.0"

